// messages.js

module.exports = {
  SOMETHING_WENT_WRONG: "Something went wrong.",
  SUCCESS: "Success",
  PRODUCT_NOT_FOUND: "Product not found.",
  PRODUCT_CREATED: "Product created successfully.",
  PRODUCT_UPDATED: "Product updated successfully.",
  PRODUCT_DELETED: "Product removed successfully.",
  PRODUCT_DOES_NOT_EXIST: "Product with given id does not exist",
  REVIEW_NOT_FOUND: "Review not found.",
  REVIEW_CREATED: "Review created successfully.",
  REVIEW_UPDATED: "Review updated successfully.",
  REVIEW_DELETED: "Review removed successfully.",
  REVIEW_DOES_NOT_EXIST: "Review with given id does not exist",
  SERVICE_NOT_FOUND: "Service not found.",
  SERVICE_CREATED: "Service created successfully.",
  SERVICE_UPDATED: "Service updated successfully.",
  SERVICE_DELETED: "Service removed successfully.",
  SERVICE_DOES_NOT_EXIST: "Service with given id does not exist",
  USER_NOT_FOUND: "User not found.",
  USER_CREATED: "User created successfully.",
  USER_UPDATED: "User updated successfully.",
  USER_DELETED: "User removed successfully.",
  USER_DOES_NOT_EXIST: "User with given id does not exist",
};
